In [1]:
import numpy as np
import pandas as pd

In [2]:
properties = pd.read_csv('data/properties_2016.csv')
train = pd.read_csv('data/train_2016_v2.csv')
field_descriptions = pd.read_excel('data/zillow_data_dictionary.xlsx')

/Users/jgzuke/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (22,32,34,49,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
properties.describe()

/Users/jgzuke/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py:4116: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,yardbuildingsqft26,yearbuilt,numberofstories,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyyear,censustractandblock
count,2.985217e+06,811519.000000,6061.000000,1628.000000,2.973755e+06,2.973767e+06,12629.000000,1.938488e+06,2.856305e+06,17096.0,...,2647.000000,2.925289e+06,682069.000000,2.930235e+06,2.942667e+06,2.973778e+06,2.917484e+06,2.953967e+06,56464.000000,2.910091e+06
mean,1.332586e+07,1.931166,7.202607,646.883292,2.209143e+00,3.088949e+00,3.725948,5.784787e+00,2.299263e+00,66.0,...,278.296562,1.964262e+03,1.401464,1.708836e+05,4.204790e+05,2.014999e+03,2.524780e+05,5.377607e+03,13.892409,6.048431e+13
std,7.909966e+06,3.148587,2.436290,538.793473,1.077754e+00,1.275859e+00,0.501700,1.805352e+00,1.000736e+00,0.0,...,369.731508,2.344132e+01,0.539076,4.020683e+05,7.263467e+05,3.683161e-02,4.450132e+05,9.183107e+03,2.581006,3.249035e+11
min,1.071172e+07,1.000000,2.000000,20.000000,0.000000e+00,0.000000e+00,1.000000,1.000000e+00,1.000000e+00,66.0,...,10.000000,1.801000e+03,1.000000,1.000000e+00,1.000000e+00,2.000000e+03,1.000000e+00,1.340000e+00,0.000000,-1.000000e+00
25%,1.164371e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.254509e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.409712e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.696019e+08,13.000000,27.000000,8516.000000,2.000000e+01,2.000000e+01,5.000000,1.200000e+01,2.000000e+01,66.0,...,6141.000000,2.015000e+03,41.000000,2.514860e+08,2.827860e+08,2.016000e+03,9.024622e+07,3.458861e+06,99.000000,4.830301e+14

In [4]:
train

       parcelid  logerror transactiondate
0      11016594    0.0276      2016-01-01
1      14366692   -0.1684      2016-01-01
2      12098116   -0.0040      2016-01-01
3      12643413    0.0218      2016-01-02
4      14432541   -0.0050      2016-01-02
5      11509835   -0.2705      2016-01-02
6      12286022    0.0440      2016-01-02
7      17177301    0.1638      2016-01-02
8      14739064   -0.0030      2016-01-02
9      14677559    0.0843      2016-01-03
10     10854446    0.3825      2016-01-03
11     11672170   -0.0161      2016-01-03
12     10949761    0.0344      2016-01-03
13     14665244    0.0816      2016-01-03
14     14148540   -0.0450      2016-01-03
15     14057104    0.0020      2016-01-03
16     17296797    0.0440      2016-01-03
17     12524288   -0.0419      2016-01-03
18     14091502   -0.0020      2016-01-03
19     10815909    0.0100      2016-01-03
20     12453853   -0.0387      2016-01-03
21     14253461    0.0218      2016-01-03
22     14001034    0.0149      2016-01-03
23     11458863    0.1151      2016-01-03
24     13957980   -0.1696      2016-01-03
25     12752047   -0.0440      2016-01-03
26     11188425   -0.0747      2016-01-03
27     14646051    0.0080      2016-01-03
28     10805063    0.0010      2016-01-03
29     12524725   -0.0534      2016-01-03
...         ...       ...             ...
90245  10757551    0.0953      2016-12-30
90246  12558267    0.0139      2016-12-30
90247  11710734    0.2095      2016-12-30
90248  14347592    0.0080      2016-12-30
90249  11341061   -0.1312      2016-12-30
90250  14027878    0.0421      2016-12-30
90251  12756771    0.0658      2016-12-30
90252  12758333    0.0030      2016-12-30
90253  11295458   -0.0294      2016-12-30
90254  12757889   -0.0111      2016-12-30
90255  11308315    0.0070      2016-12-30
90256  14353215    0.0218      2016-12-30
90257  10753416    0.0526      2016-12-30
90258  11756902    0.0889      2016-12-30
90259  11994047    0.0178      2016-12-30
90260  11440746    0.0237      2016-12-30
90261  11703478    0.0431      2016-12-30
90262  10965821   -0.2231      2016-12-30
90263  12067066    0.1398      2016-12-30
90264  11683263    0.0478      2016-12-30
90265  12062080   -0.3769      2016-12-30
90266  12265636   -0.0030      2016-12-30
90267  17109680    0.0010      2016-12-30
90268  12268527   -0.0151      2016-12-30
90269  12920746    0.0344      2016-12-30
90270  10774160   -0.0356      2016-12-30
90271  12046695    0.0070      2016-12-30
90272  12995401   -0.2679      2016-12-30
90273  11402105    0.0602      2016-12-30
90274  12566293    0.4207      2016-12-30

[90275 rows x 3 columns]

In [5]:
data_dictionary

,Feature,Description
0,'airconditioningtypeid',Type of cooling system present in the home (i...
1,'architecturalstyletypeid',"Architectural style of the home (i.e. ranch, ..."
2,'basementsqft',Finished living area below or partially below...
3,'bathroomcnt',Number of bathrooms in home including fractio...
4,'bedroomcnt',Number of bedrooms in home
5,'buildingqualitytypeid',Overall assessment of condition of the buildi...
6,'buildingclasstypeid',"The building framing type (steel frame, wood f..."
7,'calculatedbathnbr',Number of bathrooms in home including fractio...
8,'decktypeid',Type of deck (if any) present on parcel
9,'threequarterbathnbr',Number of 3/4 bathrooms in house (shower + si...
10,'finishedfloor1squarefeet',Size of the finished living area on the first...
11,'calculatedfinishedsquarefeet',Calculated total finished living area of the ...
12,'finishedsquarefeet6',Base unfinished and finished area
13,'finishedsquarefeet12',Finished living area
14,'finishedsquarefeet13',Perimeter living area
15,'finishedsquarefeet15',Total area
16,'finishedsquarefeet50',Size of the finished living area on the first...
17,'fips',Federal Information Processing Standard code ...
18,'fireplacecnt',Number of fireplaces in a home (if any)
19,'fireplaceflag',Is a fireplace present in this home
20,'fullbathcnt',"Number of full bathrooms (sink, shower + bath..."
21,'garagecarcnt',Total number of garages on the lot including ...
22,'garagetotalsqft',Total number of square feet of all garages on...
23,'hashottuborspa',Does the home have a hot tub or spa
24,'heatingorsystemtypeid',Type of home heating system
25,'latitude',Latitude of the middle of the parcel multipli...
26,'longitude',Longitude of the middle of the parcel multipl...
27,'lotsizesquarefeet',Area of the lot in square feet
28,'numberofstories',Number of stories or levels the home has
29,'parcelid',Unique identifier for parcels (lots)
30,'poolcnt',Number of pools on the lot (if any)
31,'poolsizesum',Total square footage of all pools on property
32,'pooltypeid10',Spa or Hot Tub
33,'pooltypeid2',Pool with Spa/Hot Tub
34,'pooltypeid7',Pool without hot tub
35,'propertycountylandusecode',County land use code i.e. it's zoning at the ...
36,'propertylandusetypeid',Type of land use the property is zoned for
37,'propertyzoningdesc',Description of the allowed land uses (zoning)...
38,'rawcensustractandblock',Census tract and block ID combined - also con...
39,'censustractandblock',Census tract and block ID combined - also con...
40,'regionidcounty',County in which the property is located
41,'regionidcity',City in which the property is located (if any)
42,'regionidzip',Zip code in which the property is located
43,'regionidneighborhood',Neighborhood in which the property is located
44,'roomcnt',Total number of rooms in the principal residence
45,'storytypeid',Type of floors in a multi-story house (i.e. b...
46,'typeconstructiontypeid',What type of construction material was used t...
47,'unitcnt',Number of units the structure is built into (...
48,'yardbuildingsqft17',Patio in yard
49,'yardbuildingsqft26',Storage shed/building in yard
50,'yearbuilt',The Year the principal residence was built
51,'taxvaluedollarcnt',The total tax assessed value of the parcel
52,'structuretaxvaluedollarcnt',The assessed value of the built structure on t...
53,'landtaxvaluedollarcnt',The assessed value of the land area of the parcel
54,'taxamount',The total property tax assessed for that asses...
55,'assessmentyear',The year of the property tax assessment
56,'taxdelinquencyflag',Property taxes for this parcel are past due as...
57,'taxdelinquencyyear',Year for which the unpaid propert taxes were due